### PR TITLE
Adding the tssc-operator-bundle to the catalog 

### LINKED ISSUE #16: Add new entry for the tssc-operator-bundle

### PR DESCRIPTION
**Pull request by roller1187**
Fixes #16

### CODE REVIEW

**Comment by roller1187** [comment]
This should be merged after https://github.com/RedHatGov/tssc-operator/pull/46

**Comment by andykrohg** [comment]
This will need a version bump for the catalog itself as well

**Comment by andykrohg** [comment]
Also, the CSVs and `operate.conf` need to be updated within `tssc-operator` prior to this being merged

**Review by andykrohg — APPROVED** [review]

**Comment by roller1187** [comment]
Fixes #16

**Pull request merged**
